#!/bin/bash
set -e

# Set up gopath.  Autodetect go install if necessary.
cd "$( dirname "${BASH_SOURCE[0]}" )"
export GOPATH="$PWD"/.gopath/

# Right now we need nsinit on the PATH.
PATH=$PWD/assets:$PATH

# subsection arg?
[ -z "$2" ] && SUBSECTION="./..." || SUBSECTION="./$2"


# Project details
name="repeatr"
pkg="polydawn.net/$name"
cmd="$pkg/cmd/repeatr"

# For demo runs and tests, ask them to lump all their state in one, unique dir.
mkdir -p /tmp/repeatr-test/
chmod 01777 /tmp/repeatr-test/ 2>/dev/null || true
export REPEATR_BASE="/tmp/repeatr-test/$(date +%Y.%m.%d..%H.%M.%S)..$RANDOM$RANDOM"

if [ -z "$1" ] ; then
	(
		go generate "$SUBSECTION"
		go fmt "$SUBSECTION"
		go install "$cmd" && {
			echo -e "\E[1;32minstall successful.\E[0;m\n"
		} || {
			echo -e "\E[1;41minstall failed!\E[0;m"
			exit 8
		}
		go test -short "$SUBSECTION" && {
			echo -e "\n\E[1;32mall tests green.\E[0;m"
		} || {
			echo -e "\n\E[1;41msome tests failed!\E[0;m"
			exit 4
		}
	)
else
	case "$1" in
	-)
		# passthrough for other commands
		shift
		go "$@"
		;;
	env)
		echo "GOROOT=`go env GOROOT`"
		echo "GOPATH=`go env GOPATH`"
		;;
	path)
		echo "$GOPATH"
		;;
	init)
		# it's your responsibility to do this the first time
		# (we don't do it at the front of every build because it will move submodules if you already have them, and that might not be what you want as you're plowing along)
		git submodule update --init
		;;
	test)
		go generate "$SUBSECTION"
		set +e ; shift ; shift ; set -e
		go test -i "$SUBSECTION" "$@" &&
		go test -v "$SUBSECTION" "$@" && {
			echo -e "\n\E[1;32mall tests green.\E[0;m"
		} || {
			echo -e "\n\E[1;41msome tests failed!\E[0;m"
			exit 4
		}
		;;
	bench)
		go generate "$SUBSECTION"
		set +e ; shift ; shift ; set -e
		go test -i "$SUBSECTION" "$@" &&
		go test -run=XXX -bench=. "$SUBSECTION" "$@" || {
			echo -e "\n${COLOR_BG_RED}some benchmarks failed!${COLOR_OFF}"
			exit 4
		}
		;;
	test-acceptance)
		[ -x "$GOPATH/bin/repeatr" ] || { echo "run 'goad install' first" 2>&1 ; exit 19; }
		# demo and basic acceptance scenarios should run just about anywhere
		./demo.sh -t
		./lib/integration/runAll.sh
		# repeat-thyself should usually run, but it has to sit out in travis PR-mode because of the synthetic commit which isn't actually cloneable
		if [ "$TRAVIS" == 'true' -a "$TRAVIS_PULL_REQUEST" != 'false' ]; then
			echo "skipping repeat-thyself test" 1>&2
		else
			./repeat-thyself.sh
		fi
		;;
	install)
		go generate "./..."
		go install "$cmd"
		;;
	exec)
		shift
		"$GOPATH/bin/$name" "$@"
		;;
	fmt)
		go fmt "$SUBSECTION"
		;;
	doc)
		for package in $(go list "$SUBSECTION" | sed "s#^_${PWD}#${pkg}#"); do
			echo -e "==== $package ====\n"
			godoc "$package"
			echo -e "\n\n\n"
		done
		;;
	convey)
		shift
		go install github.com/smartystreets/goconvey && "$GOPATH"/bin/goconvey "$@"
		;;
	cover)
		coverFile="$GOPATH/tmp/cover/cover.out"
		mkdir -p "$(dirname "$coverFile")"
		for package in $(go list "$SUBSECTION" | sed "s#^_${PWD}#${pkg}#"); do
			rm -f "$coverFile"
			echo "==== $package ===="
			go test -coverprofile="$coverFile" "$package" && \
			[ -f "$coverFile" ] && \
			echo ---- && \
			go tool cover -func="$coverFile" && \
			echo ---- && \
			go tool cover -html="$coverFile"
			echo ====
			echo
		done
		rm -f "$coverFile"
		;;
	validate)
		# run all validations and exit non-zero after all of them if any fail
		validators=()
		validators+=("./contrib/validate-dco")
		validators+=("./contrib/validate-gofmt")
		invalid=""
		for validator in ${validators[@]}; do
			echo -e "\E[1;34m==== checking $validator ... ====\E[0;m"
			"$validator" && {
				echo -e "\E[1;32mpassed.\E[0;m"
			} || {
				echo -e "\E[1;31mfailed!\E[0;m"
				invalid="true"
			}
			echo
			echo
		done
		echo
		[ -z "$invalid" ] && {
			echo -e "\E[1;32mall validations green.\E[0;m"
		} || {
			echo -e "\E[1;41msome validations failed!\E[0;m"
			exit 6
		}
		;;
	clean)
		rm -rf "$GOPATH/bin" "$GOPATH/pkg" "$GOPATH/tmp" "demo"
		;;
	sys)
		# i would call this `install` following make tradition, but, well, `go install` means something different, so.
		go generate "./..."
		go install "$cmd"
		cp "$GOPATH/bin/repeatr" /usr/bin/repeatr
		ls -la /usr/bin/repeatr
		repeatr --version
		;;
	*)
		echo "Usage: $0 {init|test|install|exec|fmt|doc|cover|validate|clean}" 1>&2;
		exit 1
	;;
esac

fi
